### ISSUE TITLE
podman passes down http_proxy when it shouldnt

### ISSUE THREAD

**Issue by mattp-** [podman-container-tools/podman#24838]
### Issue Description

```
$ env HTTPS_PROXY=x podman run --rm -it --entrypoint printenv scrubbed.com/rhel8 | grep HTTPS
HTTPS_PROXY=x
$ env HTTPS_PROXY=x docker run --rm -it --entrypoint printenv scrubbed.com/rhel8 | grep HTTPS
$ 
```
outside of the difference in behavior with docker; it seems like strange behavior to pass down at runtime. setting http_proxy in container.conf would be more sensible; but taking the shell's proxy var could lead to unexpected failure.

### Steps to reproduce the issue

see above excerpt

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
(master)✗ % podman version
Client:       Podman Engine
Version:      4.9.4-rhel
API Version:  4.9.4-rhel
Go Version:   go1.21.11 (Red Hat 1.21.11-1.el9_4)
Built:        Thu Aug  8 04:51:41 2024
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting
